# ==============================
# Dataset paths
# ==============================

train_root: data/part2/train
val_root: data/part2/val
test_root: data/part2/test
label_path: data/part2/train/labels.json
original_image_dir: data/part2/train/images

# ==============================
# Tuning settings for Optuna
# ==============================

batch_size: [4, 8, 16]             # Try multiple sizes
learning_rate: [1e-4, 1e-2]        # Min/Max range for optuna.suggest_float
epochs: [5, 10, 15]                  # Candidates for optuna.suggest_categorical
optimizer: ["adam", "adamw", "sgd"]
num_trials: 20                     # Number of Optuna trials to run
seed: 42
ctc_blank_index: 0

# ==============================
# Augmentation scenarios
# ==============================

augmentation_scenarios:
  - name: aug_type_A  # Default augmentation settings
    params:
      angle_range: [-15, 15]
      shear_range: [-10, 10]
      brightness_range: [0.8, 1.2]
      contrast_range: [0.8, 1.2]
      noise_std: [0.01, 0.05]
      blur_probability: 0.3
      blur_radius: [0.5, 2.0]
      lines_probability: 0.1
      line_count: [1, 3]
      line_thickness: [1, 4]

  - name: aug_type_B  # Stronger blur and noise, moderate rotation/shear
    params:
      angle_range: [-8, 8]
      shear_range: [-6, 6]
      brightness_range: [0.85, 1.15]
      contrast_range: [0.85, 1.15]
      noise_std: [0.03, 0.08]
      blur_probability: 0.5
      blur_radius: [1.0, 3.0]
      lines_probability: 0.2
      line_count: [2, 4]
      line_thickness: [2, 5]

  - name: aug_type_C  # Heavy geometric distortion, low noise
    params:
      angle_range: [-20, 20]
      shear_range: [-15, 15]
      brightness_range: [0.75, 1.25]
      contrast_range: [0.75, 1.25]
      noise_std: [0.005, 0.02]
      blur_probability: 0.2
      blur_radius: [0.3, 1.0]
      lines_probability: 0.4
      line_count: [3, 6]
      line_thickness: [1, 3]


# ==============================
# Output directories
# ==============================

output_base_dir: outputs/tuning_large/


# ==============================
# Post-analysis
# ==============================

analysis_scripts:
  - plot_curves
  - compare_trials
  - plot_charset_freq
  - plot_prediction_dist
